In [1]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[1,2,3,4],[5,6,7,8],[11,22,33,44]])


In [2]:
num_zero = np.zeros((2,2))
num_ones = np.ones((2,2))
num_eye = np.eye(2)
num_full = np.full((2,3),7)

print "zeros"
print num_zero
print "ones"
print num_ones
print "identity"
print num_eye
print "dense array"
print num_full

zeros
[[0. 0.]
 [0. 0.]]
ones
[[1. 1.]
 [1. 1.]]
identity
[[1. 0.]
 [0. 1.]]
dense array
[[7 7 7]
 [7 7 7]]


In [3]:
print a

print """Shape, Size, ndim, itemsize and dtype.name"""
print a.shape
print a.size
print a.ndim
print a.dtype.name
print a.itemsize

[[1 2 3 4]
 [5 6 7 8]]
Shape, Size, ndim, itemsize and dtype.name
(2, 4)
8
2
int64
8


In [4]:
print b

print """Shape, Size, ndim, itemsize and dtype.name"""
print b.shape
print b.size
print b.ndim
print b.dtype.name
print b.itemsize

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 22 33 44]]
Shape, Size, ndim, itemsize and dtype.name
(3, 4)
12
2
int64
8


In [5]:
num_random = np.random.random((2,5))
print "Random array"
print num_random
print num_random.shape

Random array
[[0.43024604 0.15245753 0.35833696 0.1471723  0.29022964]
 [0.82986013 0.75637921 0.52636961 0.10669276 0.85422419]]
(2, 5)


In [6]:
print num_random.reshape((5,2))

[[0.43024604 0.15245753]
 [0.35833696 0.1471723 ]
 [0.29022964 0.82986013]
 [0.75637921 0.52636961]
 [0.10669276 0.85422419]]


In [7]:
print num_random.flatten()

[0.43024604 0.15245753 0.35833696 0.1471723  0.29022964 0.82986013
 0.75637921 0.52636961 0.10669276 0.85422419]


In [8]:
# print np.resize(num_random.flatten(),(6,2))
print np.resize(num_random,(7,2))

[[0.43024604 0.15245753]
 [0.35833696 0.1471723 ]
 [0.29022964 0.82986013]
 [0.75637921 0.52636961]
 [0.10669276 0.85422419]
 [0.43024604 0.15245753]
 [0.35833696 0.1471723 ]]


In [9]:
print num_random.transpose()
print num_random.transpose().shape

[[0.43024604 0.82986013]
 [0.15245753 0.75637921]
 [0.35833696 0.52636961]
 [0.1471723  0.10669276]
 [0.29022964 0.85422419]]
(5, 2)


In [10]:
"""
Broadcast a flattened ndarray - make copies of the array
Ensure column size matches the flattened length(ndarray size)
i.e., for a random ndarray of shape: 2x5,
the column size should be 10 (as 2x5 has 10 elements when flattened)
"""
broadcast_array = np.broadcast_to(num_random.flatten(),(3,10)) # (3,10) -> makes 3 copies of the flattened array and encloses it
print broadcast_array
print broadcast_array.shape

[[0.43024604 0.15245753 0.35833696 0.1471723  0.29022964 0.82986013
  0.75637921 0.52636961 0.10669276 0.85422419]
 [0.43024604 0.15245753 0.35833696 0.1471723  0.29022964 0.82986013
  0.75637921 0.52636961 0.10669276 0.85422419]
 [0.43024604 0.15245753 0.35833696 0.1471723  0.29022964 0.82986013
  0.75637921 0.52636961 0.10669276 0.85422419]]
(3, 10)


In [11]:
"""
Expand & Squeeze:

Expand an ndarray using expand_dims; it can be done row-wise or column-wise.

Expanding a 2D array via axis=0 (row-wise) places the entire 2D array in an outer-row.
i.e., if a 2x5 array is expanded via axis 0, its new dim becomes 1x2x5

Similarly, along axis 1 places each row of the 2D array inside a separate row.
i.e., if 2x5 array is expanded via axis 1, its new dim becomes 2x1x5

In other words, axis=0 (row-wise) places all rows of the original array inside a row.
axis=1 (col-wise) places all columns of each row from the original array inside a row.
"""

print "num_random.shape: ", num_random.shape
print np.expand_dims(num_random,axis=0)
print np.expand_dims(num_random,axis=0).shape

print np.expand_dims(num_random,axis=1)
print np.expand_dims(num_random,axis=1).shape

print "broadcast_array.shape: ", broadcast_array.shape
print np.expand_dims(broadcast_array,axis=0)
print np.expand_dims(broadcast_array,axis=0).shape

print np.expand_dims(broadcast_array,axis=1)
print np.expand_dims(broadcast_array,axis=1).shape

num_random.shape:  (2, 5)
[[[0.43024604 0.15245753 0.35833696 0.1471723  0.29022964]
  [0.82986013 0.75637921 0.52636961 0.10669276 0.85422419]]]
(1, 2, 5)
[[[0.43024604 0.15245753 0.35833696 0.1471723  0.29022964]]

 [[0.82986013 0.75637921 0.52636961 0.10669276 0.85422419]]]
(2, 1, 5)
broadcast_array.shape:  (3, 10)
[[[0.43024604 0.15245753 0.35833696 0.1471723  0.29022964 0.82986013
   0.75637921 0.52636961 0.10669276 0.85422419]
  [0.43024604 0.15245753 0.35833696 0.1471723  0.29022964 0.82986013
   0.75637921 0.52636961 0.10669276 0.85422419]
  [0.43024604 0.15245753 0.35833696 0.1471723  0.29022964 0.82986013
   0.75637921 0.52636961 0.10669276 0.85422419]]]
(1, 3, 10)
[[[0.43024604 0.15245753 0.35833696 0.1471723  0.29022964 0.82986013
   0.75637921 0.52636961 0.10669276 0.85422419]]

 [[0.43024604 0.15245753 0.35833696 0.1471723  0.29022964 0.82986013
   0.75637921 0.52636961 0.10669276 0.85422419]]

 [[0.43024604 0.15245753 0.35833696 0.1471723  0.29022964 0.82986013
   0.7563

In [12]:
"""
Expand & Squeeze:

Squeeze: Rolls back the dimensions of a previously expanded array.
"""

axis_0_expanded_array = np.expand_dims(num_random,axis=0)
axis_1_expanded_array = np.expand_dims(num_random,axis=1)

print "before: ", axis_0_expanded_array.shape
print "after: ", np.squeeze(axis_0_expanded_array).shape

print "before: ", axis_1_expanded_array.shape
print "after: ", np.squeeze(axis_1_expanded_array).shape

before:  (1, 2, 5)
after:  (2, 5)
before:  (2, 1, 5)
after:  (2, 5)


In [13]:
"""
Concatenate & Stack

Concatenate: 
Row-wise would pile the arrays along the rows
Col-wise would arrange the arrays along the columns

Ensure that the dimension of the concatenated arrays must match except for the axis along which they're concatenated.
i.e., 2x5 and 3x5 arrays can be concatenated along axis 0 (row), but not with 3x3
In the above example, the row dimensions need not match (2 rows and 3 rows respectively). Similarly for axis=1 (col-wise).

Note: Scalar addition of numpy arrays adds scalar to each element
"""
print "num_random.shape: ", num_random.shape
print np.concatenate((num_random, num_random), axis=0)
print "concatenated dim: ", np.concatenate((num_random, num_random), axis=0).shape
print np.concatenate((num_random, num_random), axis=1)
print "concatenated dim: ", np.concatenate((num_random, num_random), axis=1).shape


num_random.shape:  (2, 5)
[[0.43024604 0.15245753 0.35833696 0.1471723  0.29022964]
 [0.82986013 0.75637921 0.52636961 0.10669276 0.85422419]
 [0.43024604 0.15245753 0.35833696 0.1471723  0.29022964]
 [0.82986013 0.75637921 0.52636961 0.10669276 0.85422419]]
concatenated dim:  (4, 5)
[[0.43024604 0.15245753 0.35833696 0.1471723  0.29022964 0.43024604
  0.15245753 0.35833696 0.1471723  0.29022964]
 [0.82986013 0.75637921 0.52636961 0.10669276 0.85422419 0.82986013
  0.75637921 0.52636961 0.10669276 0.85422419]]
concatenated dim:  (2, 10)


In [19]:
"""
Stacking:

Ensure that the stacked arrays are of the same shape.

Here, row-wise stacking (axis=0), stacks all columns in each row of the arrays.
For example, 
M = [[m11 m12][m21 m22]] is row stacked with N = [[n11 n12][n21 n22]]

Result is:

[
    [
        [m11 m12] # row1 of M
        [m21 m22] # row2 of M
    ]
    [
        [n11 n12] # row1 of N
        [n21 n22] # row2 of N
    ]
]


Similarly col-wise stacking (axis=1), stacks all the rows in each column for the arrays involved.
For example,

M = [[m11 m12][m21 m22]] is row stacked with N = [[n11 n12][n21 n22]]

Result is:

[
    [
        [m11 m12] # row1 of M
        [n11 n12] # row1 of N
    ]
    [
        [m21 m22] # row2 of M
        [n21 n22] # row2 of N
    ]
]
"""
new_num_random = np.random.random((2,5))
print new_num_random
print "new_num_random: ", new_num_random.shape

print num_random
print "num_random: ", num_random.shape

print np.stack((num_random, new_num_random), axis=0)
print "num_random row stacked: ", np.stack((num_random, new_num_random), axis=0).shape

print np.stack((num_random, new_num_random), axis=1)
print "num_random col stacked: ", np.stack((num_random, new_num_random), axis=1).shape

[[0.00411527 0.4141311  0.41154378 0.6776047  0.21344928]
 [0.18410272 0.87850643 0.6860854  0.82662243 0.71196314]]
new_num_random:  (2, 5)
[[0.43024604 0.15245753 0.35833696 0.1471723  0.29022964]
 [0.82986013 0.75637921 0.52636961 0.10669276 0.85422419]]
num_random:  (2, 5)
[[[0.43024604 0.15245753 0.35833696 0.1471723  0.29022964]
  [0.82986013 0.75637921 0.52636961 0.10669276 0.85422419]]

 [[0.00411527 0.4141311  0.41154378 0.6776047  0.21344928]
  [0.18410272 0.87850643 0.6860854  0.82662243 0.71196314]]]
num_random row stacked:  (2, 2, 5)
[[[0.43024604 0.15245753 0.35833696 0.1471723  0.29022964]
  [0.00411527 0.4141311  0.41154378 0.6776047  0.21344928]]

 [[0.82986013 0.75637921 0.52636961 0.10669276 0.85422419]
  [0.18410272 0.87850643 0.6860854  0.82662243 0.71196314]]]
num_random col stacked:  (2, 2, 5)


In [33]:
"""
Splitting: split, hsplit & vsplit

Returns a list of arrays equal to the number of splits. Ensure that equal division is achieved from the defined splits.

hsplit - equivalent to split by column (axis=1)
vsplit - equivalent to split by rows (axis=0)
"""

print np.split(num_random,2) # row split by default

# np.split(num_random,5) -- throws error

print np.split(num_random,5,axis=1) # column split

print "hsplit below: "
print np.hsplit(num_random,5)

print "vsplit below: "
print np.vsplit(num_random,2)


[array([[0.43024604, 0.15245753, 0.35833696, 0.1471723 , 0.29022964]]), array([[0.82986013, 0.75637921, 0.52636961, 0.10669276, 0.85422419]])]
[array([[0.43024604],
       [0.82986013]]), array([[0.15245753],
       [0.75637921]]), array([[0.35833696],
       [0.52636961]]), array([[0.1471723 ],
       [0.10669276]]), array([[0.29022964],
       [0.85422419]])]
hsplit below: 
[array([[0.43024604],
       [0.82986013]]), array([[0.15245753],
       [0.75637921]]), array([[0.35833696],
       [0.52636961]]), array([[0.1471723 ],
       [0.10669276]]), array([[0.29022964],
       [0.85422419]])]
vsplit below: 
[array([[0.43024604, 0.15245753, 0.35833696, 0.1471723 , 0.29022964]]), array([[0.82986013, 0.75637921, 0.52636961, 0.10669276, 0.85422419]])]


In [47]:
"""
Insert, Append & Delete

Apply on a flattened/1D array

Append: Appends newer elements.
        If not a 1D array, it flattens the input array and appends the newer elements.

Insert: Inserts newer elements at the defined index position.
        Not sure about axis argument. Figure out why error is thrown when axis=1
    
Delete: Delete the element at the specified index position.
        If not a 1D array, it flattens the array before deletion.
"""

print num_random
print num_random.shape

print "Append: ", np.append(num_random,[1,0,0,0,0])
print "Appended shape: ", np.append(num_random,[1,0,0,0,0]).shape

print "Insert: ", np.insert(num_random.flatten(), 2, [1.12, 2.221], axis=0)
print "Insert shape: ", np.insert(num_random.flatten(), 2, [1.12, 2.221], axis=0).shape

print "Delete: ", np.delete(num_random, 4)

[[0.43024604 0.15245753 0.35833696 0.1471723  0.29022964]
 [0.82986013 0.75637921 0.52636961 0.10669276 0.85422419]]
(2, 5)
Append:  [0.43024604 0.15245753 0.35833696 0.1471723  0.29022964 0.82986013
 0.75637921 0.52636961 0.10669276 0.85422419 1.         0.
 0.         0.         0.        ]
Appended shape:  (15,)
Insert:  [0.43024604 0.15245753 1.12       2.221      0.35833696 0.1471723
 0.29022964 0.82986013 0.75637921 0.52636961 0.10669276 0.85422419]
Insert shape:  (12,)
Delete:  [0.43024604 0.15245753 0.35833696 0.1471723  0.82986013 0.75637921
 0.52636961 0.10669276 0.85422419]


In [51]:
"""
Element-wise operations:

np.addition --> numpy + numpy
np.subtract --> numpy - numpy
np.multiply --> numpy * numpy
np.sqrt --> Square root each element in the array

Note: To divide ensure it is converted to float before performing division operation:
i.e., 

1. * numpy/numpy
"""

print np.add(num_random,new_num_random)
print np.subtract(num_random, new_num_random)
print np.multiply(num_random, new_num_random)
print 1. * num_random/new_num_random

[[0.43436131 0.56658863 0.76988074 0.824777   0.50367892]
 [1.01396285 1.63488564 1.21245501 0.93331519 1.56618733]]
[[ 0.42613077 -0.26167357 -0.05320681 -0.5304324   0.07678036]
 [ 0.64575741 -0.12212723 -0.15971579 -0.71992967  0.14226106]]
[[0.00177058 0.0631374  0.14747135 0.09972464 0.06194931]
 [0.15277951 0.664484   0.36113451 0.08819463 0.60817614]]
[[104.54860149   0.36813833   0.87071408   0.21719492   1.35971246]
 [  4.50759293   0.86098312   0.76720713   0.12907073   1.1998152 ]]


In [65]:
"""
Aggregations:

np.sum(), np.min(), np.max(), np.mean(), np.median(), np.std(), np.cumsum()

also,
np.unique()

Note: These operations can be performed row/col-wise as well.
"""

print np.sum(num_random)
print np.sum(num_random, axis=0) # col-wise sum ; sum of all rows, for each column
print "----------------------------------------"
print np.min(num_random)
print np.min(num_random, axis=1)
print "----------------------------------------"
print np.max(num_random)
print np.max(num_random, axis=0)
print "----------------------------------------"
print np.mean(num_random)
print np.median(num_random, axis=1)
print np.std(num_random, axis=1)
print "----------------------------------------"
print np.cumsum(num_random)
print np.cumsum(num_random, axis=1)
print "----------------------------------------"
print np.unique(num_random)
print np.unique(num_random,axis=1)

4.45196836853457
[1.26010617 0.90883673 0.88470657 0.25386506 1.14445383]
----------------------------------------
0.10669275688538182
[0.1471723  0.10669276]
----------------------------------------
0.8542241918902145
[0.82986013 0.75637921 0.52636961 0.1471723  0.85422419]
----------------------------------------
0.445196836853457
[0.29022964 0.75637921]
[0.11192188 0.27914596]
----------------------------------------
[0.43024604 0.58270357 0.94104053 1.08821283 1.37844248 2.2083026
 2.96468181 3.49105142 3.59774418 4.45196837]
[[0.43024604 0.58270357 0.94104053 1.08821283 1.37844248]
 [0.82986013 1.58623933 2.11260894 2.2193017  3.07352589]]
----------------------------------------
[0.10669276 0.1471723  0.15245753 0.29022964 0.35833696 0.43024604
 0.52636961 0.75637921 0.82986013 0.85422419]
[[0.1471723  0.15245753 0.29022964 0.35833696 0.43024604]
 [0.10669276 0.75637921 0.85422419 0.52636961 0.82986013]]


In [71]:
"""
Inner product (np.dot) & Matrix Multiplication
"""

X = np.random.randint(7,size=(3,2))
w = np.random.random((2,3))

print w
print "----------------------------------------"
print X
print "----------------------------------------"

print "Dot: ", np.dot(w,X)

[[0.31098053 0.42749587 0.90351884]
 [0.39161818 0.94947178 0.19356277]]
----------------------------------------
[[0 2]
 [6 0]
 [1 3]]
----------------------------------------
Dot:  [[3.46849405 3.3325176 ]
 [5.89039344 1.36392466]]
